### ISSUE TITLE
Do not work with pre-commit

### ISSUE THREAD

**Issue by Bysmyyr** [sqlalchemyorg/zimports#2]
I did not find the way to run with pre-commit hooks.

[INFO] Initializing environment for https://github.com/sqlalchemyorg/zimports.
An unexpected error has occurred: CalledProcessError: Command: ('/usr/libexec/git-core/git', 'checkout', '')
Return code: 128
Expected return code: 0
Output: (none)
Errors: 
    fatal: empty string is not a valid pathspec. please use . instead if you meant to match all paths

**Comment by Bysmyyr** [comment]
And somehow I need to exclude venv folder

**Comment by zzzeek** [comment]
hi there-

not sure, I'm using it with pre-commit right now, here's my config:

```
repos:
-   repo: https://github.com/python/black/
    rev: master
    hooks:
    -   id: black
        args: [-l 79]

-   repo: https://github.com/sqlalchemyorg/zimports/
    rev: master
    hooks:
    -   id: zimports

```


it looks like you are having a problem with pre-commit itself maybe ask them ?  https://github.com/pre-commit/pre-commit

**Comment by Bysmyyr** [comment]
Ah, found the error. The rev was ''. Should it be better that the readme example has master and comment to change it if needed?

**Comment by zzzeek** [comment]
oh wow I didn't even remember someone added that snippet to the README, sure

**Comment by asottile** [comment]
you shouldn't use [`rev: master`](https://pre-commit.com/#using-the-latest-version-for-a-repository) which is why it was left as a placeholder :man_shrugging:

**Comment by zzzeek** [comment]
hi -

please tell me how it's supposed to be and what this user should do

**Comment by asottile** [comment]
the value there should be an immutable tag or a sha -- it seems like there aren't any git tags in this repo yet so they would use something like `58545832` (the current revision of master).

there's ~three approaches that I've taken when documenting this in my repos:

1. Use the latest version
- PRO: copy paste, ready to go
- CON: when releasing, it's another place you need to update the version number
- EXAMPLE: https://github.com/asottile/pyupgrade#as-a-pre-commit-hook

2. Use an empty string with a comment (as is being done here)
- PRO: no need to update when releasing
- CON: user needs to retrieve a value
- EXAMPLE: (this repo)

3. Use some value and suggest `pre-commit autoupdate`
- PRO: copy pasteable
- CON: the value here is not always up-to-date and may attract PRs which attempt to upgrade it
- EXAMPLE: (none yet that I could find :S)

It's probably / possible that `pre-commit` should allow some sort of sigil value that gets updated on first installation :thinking: maybe I'll look into implementing something like that -- or just treating the empty string as a special case
