### ISSUE TITLE
Fix typing issues

### ISSUE THREAD

**Issue by CaselIT** [sqlalchemyorg/zimports#25]
Some issues when using types in code have come up:

- [ ] https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3447/comment/83a4e453_d20a3bbd/
- [x] https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3447/comment/569393c5_a3de5fd8/

**Comment by zzzeek** [comment]
and also (will open a separate issue, this is easier to fix hopefully): https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3525/2/lib/sqlalchemy/util/_concurrency_py3k.py#19

**Comment by zzzeek** [comment]
for https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3447/comment/569393c5_a3de5fd8/ this is #33

**Comment by zzzeek** [comment]
the other issue is #12
