### ISSUE TITLE
Possibility to retain `from module import x, y` permitted by PEP8

### ISSUE THREAD

**Issue by ashwinvis** [sqlalchemyorg/zimports#3]
Would it be possible to retain the [example in PEP8](https://www.python.org/dev/peps/pep-0008/#imports) as it is, perhaps optionally:

```python
from subprocess import Popen, PIPE
```

and not breaking them up as:

```python
from subprocess import Popen
from subprocess import PIPE
```

**Comment by ashwinvis** [comment]
Closing because `isort` seems to do what we need. Removing unused imports is done better by `zimports` of course, but is not usually needed.

**Comment by zzzeek** [comment]
I wrote zimports to do imports on one line, I've worked for years with imports that have tons of symbols all on one line and I've decided it's a mistake.      They make git merges difficult, it makes linting difficult, they make readability difficult, etc.
