### ISSUE TITLE
Add option to parallelize files

### ISSUE THREAD

**Issue by CaselIT** [sqlalchemyorg/zimports#38]
Since to support typing zimports has to do 3 passes for each file, it's not the fastest, and sqlalchemy has a lot of files.

Probably on by default with option to disable.

**Comment by zzzeek** [comment]
hm does black have that?

**Comment by CaselIT** [comment]
sure, black parallelize by default to all available cores.
can be customized by specifying  `-W, --workers INTEGER RANGE     Number of parallel workers `

**Comment by sigmavirus24** [comment]
Flake8 also has this and does it by default on all except Windows? But only because of legacy plugin reasons that shouldn't be relevant to y'all

**Comment by CaselIT** [comment]
Using a pool it should be fairly easy to parallelize
