### ISSUE TITLE
detect Python source file encoding including magic comment properly, use it explicitly when file is read and written to.

### ISSUE THREAD

**Issue by commentator8** [sqlalchemyorg/zimports#8]
Hi,

I am running this with pre-commit (in the process of setting it up) and encountering issues where the file i'm running it on has a "# -*- coding: utf-8 -*-" up the top, but in the zimports script it uses `with open(filename) as file_` in `_run_file` which results in the platform default and a UnicodeDecodeError.

I take it this isn't completely unicode safe yet?

**Comment by zzzeek** [comment]
maybe not in python 2?    I use zimports on all my code and there is plenty of utf-8 characters being handled.    I would assume my platform encoding is already utf-8 which is pretty common.   Please provide more specifics.

**Comment by zzzeek** [comment]
this would go some way towards reading the magic comment and interpreting other encodings but we it isn't getting it on the write side unless utf-8 is used.   per pep 3120 alternate encodings are still supported.


```

diff --git a/zimports.py b/zimports.py
index a44373f..c7c48a8 100644
--- a/zimports.py
+++ b/zimports.py
@@ -556,9 +551,13 @@ def _lines_with_newlines(lines):
         yield line + "\n"


+def _read_python_source(filename):
+    with open(filename, "rb") as file_:
+        return importlib.util.decode_source(file_.read()).split("\n")
+
+
 def _run_file(options, filename):
-    with open(filename) as file_:
-        source_lines = [line.rstrip() for line in file_]
+    source_lines = [line.rstrip() for line in _read_python_source(filename)]
     if options.keep_unused:
         if options.heuristic_unused:
             raise Exception(
@@ -604,7 +603,7 @@ def _run_file(options, filename):
             )
         else:
             if stats["is_changed"]:
-                with open(filename, "w") as file_:
+                with open(filename, "w", encoding="utf-8") as file_:
                     file_.writelines(_lines_with_newlines(result))



```

**Comment by zzzeek** [comment]
here's what black does.    I can accept a PR that makes use of this, grabbing the file's encoding, ensuring it is used on the write back, and adds test files.

https://github.com/psf/black/blob/master/black.py#L775

```
def decode_bytes(src: bytes) -> Tuple[FileContent, Encoding, NewLine]:
    """Return a tuple of (decoded_contents, encoding, newline).
    `newline` is either CRLF or LF but `decoded_contents` is decoded with
    universal newlines (i.e. only contains LF).
    """
    srcbuf = io.BytesIO(src)
    encoding, lines = tokenize.detect_encoding(srcbuf.readline)
    if not lines:
        return "", encoding, "\n"

    newline = "\r\n" if b"\r\n" == lines[0][-2:] else "\n"
    srcbuf.seek(0)
    with io.TextIOWrapper(srcbuf, encoding) as tiow:
        return tiow.read(), encoding, newline
```

**Comment by commentator8** [comment]
Hi,

Thanks for the prompt response. I have to be honest, i tried isort and found that it did work properly - and that suffices for my use purposes.  I dont currently have the time for a PR - i primarily wanted to alert about the issue. Just to respond to your initial post - my platform (windows) encoding is cp1255 which results in the issue.

`Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm 2019.1.3\helpers\pydev\pydevd.py", line 1758, in <module>
    main()
  File "C:\Program Files\JetBrains\PyCharm 2019.1.3\helpers\pydev\pydevd.py", line 1752, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "C:\Program Files\JetBrains\PyCharm 2019.1.3\helpers\pydev\pydevd.py", line 1147, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm 2019.1.3\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:/Users/user/AppData/Local/Programs/Python/Python38-32/Lib/site-packages/zimports.py", line 702, in <module>
    main()
  File "C:/Users/user/AppData/Local/Programs/Python/Python38-32/Lib/site-packages/zimports.py", line 698, in main
    _run_file(options, filename)
  File "C:/Users/user/AppData/Local/Programs/Python/Python38-32/Lib/site-packages/zimports.py", line 561, in _run_file
    source_lines = [line.rstrip() for line in file_]
  File "C:/Users/user/AppData/Local/Programs/Python/Python38-32/Lib/site-packages/zimports.py", line 561, in <listcomp>
    source_lines = [line.rstrip() for line in file_]
  File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\encodings\cp1255.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8a in position 2126: character maps to <undefined>`
